name: Playwright Tests
on:
  - pull_request
  - workflow_dispatch
permissions:
  checks: write
  pull-requests: write
  contents: write
jobs:
  test:
    name: Test (${{ matrix.shard }} / ${{ strategy.job-total}})
    continue-on-error: true
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [ 1, 2, 3, 4 ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Build env and build synpress cache
      run: yarn dev & npx wait-on http://localhost:3000 --timeout 40000 --log-level silent && yarn build:cache:ci --force tests/wallet-setup/
    - name: Run Playwright tests
      env:
        PLAYWRIGHT_JSON_OUTPUT_NAME: report-${{ matrix.shard }}.json
      run: |
        yarn run test:ci:e2e \
          --shard ${{ matrix.shard }}/${{ strategy.job-total }} \
          --reporter=json
    - uses: daun/playwright-report-summary@v3
      if: always()
      with:
        report-file: report-${{ matrix.shard }}.json
        report-tag: ${{ matrix.shard }}
        comment-title: 'Test results (${{ matrix.shard }}/${{ strategy.job-total }})'
